title: Maisie Sadler
email: your-email@example.com
description: >-
  Software Engineer working for TrueLayer in London.
url: "https://maisiesadler.github.io/"
github_username: maisiesadler

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
