title: Maisie Sadler
description: >-
  Software Engineer working for TrueLayer in London.
url: "https://maisiesadler.github.io/"
github_username: maisiesadler

remote_theme: pages-themes/midnight@v0.2.0
plugins:
 - jekyll-feed
 - jekyll-remote-theme
